"""add is_admin to users

Revision ID: bf1822f59a46
Revises: 
Create Date: 2026-03-20 02:52:13.209268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf1822f59a46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.alter_column('reports', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('violations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('violations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_violations_locaitons', table_name='violations', postgresql_using='gist')
    op.create_index('idx_violations_location', 'violations', ['location'], unique=False, postgresql_using='gist')
    op.drop_constraint('violations_ward_id_fkey', 'violations', type_='foreignkey')
    op.create_foreign_key(None, 'violations', 'wards', ['ward_id'], ['id'])
    op.alter_column('wards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('wards_name_key', 'wards', type_='unique')
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wards_name'), table_name='wards')
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.create_unique_constraint('wards_name_key', 'wards', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('wards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.create_foreign_key('violations_ward_id_fkey', 'violations', 'wards', ['ward_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_violations_location', table_name='violations', postgresql_using='gist')
    op.create_index('idx_violations_locaitons', 'violations', ['location'], unique=False, postgresql_using='gist')
    op.alter_column('violations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('violations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'is_admin')
    op.alter_column('reports', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
